import Hashmap from "./hashmap.js";

const test = new Hashmap(16, 0.75)

test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')

console.log(`the value of apple should be red: ${test.get('apple')}`)
console.log(`length of hashmap: ${test.length()}`)
console.log('updating value of apple to be green')
test.set('apple', 'green')
console.log(`new apple value: ${test.get('apple')}`)
test.set('apple', 'blue')
console.log(`new apple value should be blue: ${test.get('apple')}`)
console.log(`length of hashmap after setting same key: ${test.length()}`)
console.log(`current hashmap capacity: ${test.capacity}`)
console.log(`current load_factor: ${test.load_factor}`)

test.set('moon', 'silver')

console.log(`Added moon, capacity doubled: ${test.capacity}`)
console.log(`length increased by 1: ${test.length()}`)
console.log(test.entries())
test.set('apple', 'yellow')
console.log(test.entries())
